# Generated by Django 4.0.4 on 2022-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(default=1, null=True, to='users.comments'),
        ),
    ]
