# Generated by Django 4.0.4 on 2022-06-06 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_remove_image_comment_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='like_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
