# Generated by Django 4.0.4 on 2022-06-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_comments_comment_remove_image_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
