# Generated by Django 4.0.4 on 2022-06-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
